version: "3.7"

services:
  search-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-ui
    ports:
      - "3000:80"
    networks:
      - search-ui-network
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  search-ui-network:
    driver: bridge
  elastic:
    driver: bridge
